# Description: Top level Makefile Multicast Server
#
# Authors: Taran and Kyle
# Class:   CMPT 332 - Fall 2015

# Directories to include in the build

EXE = multicast_server send_client recv_client

all:
	cd src; make; mv ${EXE} ..

clean: 
	${RM} ${EXE} *.o;
